apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kbur
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kbur
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kbur
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kbur
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kbur
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bhkz-tenant/rhtap-demo-app/hacbs-test-project-kbur@sha256:b55459bb46bc66580a6b7e34fe1678dfa1238c2184fb6e52112e0ef6fc5ccf89
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
