apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kbur
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bhkz-tenant/rhtap-demo-app/hacbs-test-project-kbur@sha256:b55459bb46bc66580a6b7e34fe1678dfa1238c2184fb6e52112e0ef6fc5ccf89
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
